# Generated by Django 5.2.12 on 2026-03-05 06:23

import app_assets.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=app_assets.models.asset_upload_to)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public'), ('unlisted', 'unlisted')], default='private', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'uploaded'), ('processing', 'processing'), ('ready', 'ready'), ('blocked', 'blocked')], default='uploaded', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
