# Generated by Django 5.2.12 on 2026-03-05 07:40

import app_assets.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelasset',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('processing', '处理中'), ('ready', '就绪'), ('blocked', '已禁用')], default='uploaded', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelasset',
            name='visibility',
            field=models.CharField(choices=[('private', '私有'), ('public', '公开'), ('unlisted', '不公开（仅链接可访问）')], default='private', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, null=True, upload_to=app_assets.models.avatar_upload_to)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
